const SB_URL=Deno.env.get('SUPABASE_URL')||'';
const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const BOT=Deno.env.get('TELEGRAM_BOT_TOKEN')||'';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const enc=(v)=>encodeURIComponent(String(v??''));
async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function secret(){return (await sha(BOT+':pegas-bot-api')).slice(0,64)}
async function db(path,init={}){const h=new Headers(init.headers||{});h.set('apikey',KEY);h.set('authorization',`Bearer ${KEY}`);h.set('prefer','return=representation');if(init.body)h.set('content-type','application/json');const r=await fetch(`${SB_URL}/rest/v1/${path}`,{...init,headers:h});const t=await r.text();if(!r.ok)throw new Error(`DB ${r.status}: ${t}`);return t?JSON.parse(t):null}
async function loadUser(id){return (await db(`app_users?select=*&id=eq.${enc(id)}&active=eq.true&limit=1`))?.[0]||null}
async function perms(u){if(u.role==='admin')return ['*'];return (await db(`role_permissions?select=permission&role=eq.${enc(u.role)}`)).map(x=>x.permission)}
const can=(ps,p)=>ps.includes('*')||ps.includes(p);
function orderNo(){return `ORD-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(Date.now()).slice(-6)}`}
async function audit(u,action,type,id,payload={}){try{await db('audit_log',{method:'POST',body:JSON.stringify({actor_user_id:u.id,action,entity_type:type,entity_id:id,payload})})}catch(e){console.error(e)}}
async function customerByName(u,name){if(u.role==='client')return u.customer_id?(await db(`customers?select=*&company_id=eq.${u.company_id}&id=eq.${u.customer_id}&limit=1`))?.[0]:null;const exact=(await db(`customers?select=*&company_id=eq.${u.company_id}&name=ilike.${enc(name)}&limit=1`))?.[0];if(exact)return exact;const rows=await db(`customers?select=*&company_id=eq.${u.company_id}&name=ilike.${enc('%'+name+'%')}&limit=5`);return rows?.length===1?rows[0]:null}
function normRegime(x){const s=String(x||'').toLowerCase();if(['frozen','chilled','dry','ph8','ph25'].includes(s))return s;return null}
async function createOrder(u,ps,d){if(u.role==='client'){if(!can(ps,'orders.create_own'))throw new Error('FORBIDDEN')}else if(!can(ps,'orders.create'))throw new Error('FORBIDDEN');const customer=await customerByName(u,d.customer);if(!customer)throw new Error('CUSTOMER_NOT_FOUND');const row=(await db('orders',{method:'POST',body:JSON.stringify({company_id:u.company_id,customer_id:customer.id,order_no:orderNo(),status:'draft',delivery_type:d.delivery_type||'pickup',cargo_name:d.cargo||null,cargo_category:d.cargo_category||null,temperature_mode:normRegime(d.regime),pickup_address:d.pickup||null,pickup_window_from:d.ready_at||null,destination_address:d.destination||null,destination_city:d.destination_city||d.destination||null,pallet_count:Number(d.pallets)||1,total_weight_kg:Number(d.weight_kg)||0,priority:d.priority||'normal',notes:d.note||'Создано через Telegram после подтверждения пользователя',created_by:u.id})}))?.[0];await audit(u,'telegram.create_order','orders',row.id,{source:'telegram',confirmed:true});return {order:row,customer}}
async function status(u,sscc){let p=`pallets?select=*&company_id=eq.${u.company_id}&sscc=eq.${enc(sscc)}`;if(u.role==='client'){if(!u.customer_id)return null;p+=`&customer_id=eq.${u.customer_id}`}if(u.role==='driver'){const trips=await db(`trips?select=id&company_id=eq.${u.company_id}&driver_user_id=eq.${u.id}`),pickups=await db(`pickup_tasks?select=id&company_id=eq.${u.company_id}&driver_user_id=eq.${u.id}`),tids=trips.map(x=>x.id),pids=pickups.map(x=>x.id);const row=(await db(p+'&limit=1'))?.[0];if(!row)return null;if((row.trip_id&&!tids.includes(row.trip_id))&&(row.pickup_task_id&&!pids.includes(row.pickup_task_id)))return null;return row}return (await db(p+'&limit=1'))?.[0]||null}
function startOf(period){const d=new Date();if(period==='day'){d.setHours(0,0,0,0);return d}if(period==='week'){d.setDate(d.getDate()-7);return d}if(period==='month'){d.setDate(d.getDate()-30);return d}return new Date(Date.now()-7*86400000)}
async function report(u,body){const ps=await perms(u);if(u.role!=='client'&&!can(ps,'dashboard.read')&&!can(ps,'analytics.read'))throw new Error('FORBIDDEN');let from=body.from?new Date(body.from):startOf(body.period||'week'),to=body.to?new Date(body.to):new Date();if(isNaN(+from)||isNaN(+to))throw new Error('BAD_PERIOD');let of=`company_id=eq.${u.company_id}&created_at=gte.${enc(from.toISOString())}&created_at=lte.${enc(to.toISOString())}`,pf=`company_id=eq.${u.company_id}&created_at=gte.${enc(from.toISOString())}&created_at=lte.${enc(to.toISOString())}`;if(u.role==='client'){if(!u.customer_id)throw new Error('CLIENT_NOT_LINKED');of+=`&customer_id=eq.${u.customer_id}`;pf+=`&customer_id=eq.${u.customer_id}`}const [orders,pallets,trips]=await Promise.all([db(`orders?select=*&${of}&limit=1500`),db(`pallets?select=*&${pf}&limit=2500`),u.role==='client'?[]:db(`trips?select=*&company_id=eq.${u.company_id}&created_at=gte.${enc(from.toISOString())}&created_at=lte.${enc(to.toISOString())}&limit=1000`)]);const weight=pallets.reduce((s,p)=>s+Number(p.weight_kg||0),0),late=pallets.filter(p=>p.deadline_at&&new Date(p.deadline_at)<to&&!['delivered','closed'].includes(p.status)),delivered=pallets.filter(p=>['delivered','closed'].includes(p.status));const clientIds=[...new Set(orders.map(o=>o.customer_id).filter(Boolean))];let customers=[];if(clientIds.length)customers=await db(`customers?select=id,name&id=in.(${clientIds.join(',')})`);const names=Object.fromEntries(customers.map(c=>[c.id,c.name])),byClient={};for(const o of orders)byClient[names[o.customer_id]||'Без заказчика']=(byClient[names[o.customer_id]||'Без заказчика']||0)+1;const topClients=Object.entries(byClient).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,count])=>({name,count})),byDest={};for(const p of pallets)if(p.destination_city)byDest[p.destination_city]=(byDest[p.destination_city]||0)+1;const topDestinations=Object.entries(byDest).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,count])=>({name,count}));return {from:from.toISOString(),to:to.toISOString(),orders:orders.length,pallets:pallets.length,total_weight_kg:Math.round(weight),trips:trips.length,delivered:delivered.length,sla_overdue:late.length,top_clients:topClients,top_destinations:topDestinations}}
Deno.serve(async req=>{try{if(req.method!=='POST')return new Response(JSON.stringify({ok:false,error:'POST only'}),{status:405,headers:H});if((req.headers.get('x-pegas-bot-secret')||'')!==await secret())return new Response(JSON.stringify({ok:false,error:'Unauthorized'}),{status:401,headers:H});const body=await req.json();if(body.action==='health')return new Response(JSON.stringify({ok:true,version:1}),{headers:H});const u=await loadUser(body.user_id);if(!u)return new Response(JSON.stringify({ok:false,error:'USER_NOT_FOUND'}),{status:401,headers:H});const ps=await perms(u);if(body.action==='resolve_customer'){const c=await customerByName(u,body.name||'');return new Response(JSON.stringify({ok:true,customer:c}),{headers:H})}if(body.action==='create_order'){const x=await createOrder(u,ps,body.data||{});return new Response(JSON.stringify({ok:true,...x}),{headers:H})}if(body.action==='status'){const p=await status(u,body.sscc||'');return new Response(JSON.stringify({ok:true,pallet:p}),{headers:H})}if(body.action==='report'){const r=await report(u,body);return new Response(JSON.stringify({ok:true,report:r}),{headers:H})}return new Response(JSON.stringify({ok:false,error:'Unknown action'}),{status:400,headers:H})}catch(e){const msg=e?.message||String(e),status=msg==='FORBIDDEN'?403:msg==='CUSTOMER_NOT_FOUND'?404:400;return new Response(JSON.stringify({ok:false,error:msg}),{status,headers:H})}});